name: update-clash

on:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"

permissions:
  contents: write   # 👈 خیلی مهم برای اجازه push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # 👈 مهم برای جلوگیری از conflict

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run builder
        run: python main.py

      - name: Commit and push safely
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add clash.yaml

          git commit -m "update" || exit 0

          # 👇 مهم‌ترین بخش (جلوگیری از push conflict)
          git pull --rebase origin main || true

          git push origin main
