name: update-clash

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install requests pyyaml

      - run: python main.py

      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add clash.yaml
          git commit -m "update" || echo "no changes"
          git push
